# Generated by Django 4.1 on 2022-09-05 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 11, 41, 28, 532856, tzinfo=datetime.timezone.utc)),
        ),
    ]
